Fix CI
srobo/inventory pull request #11
Opened 2023-09-17 18:55 UTC by WillB97

Use repo version of sr-tools

2023-09-17 19:00 UTC, raccube approved these changes

2023-09-17 19:02 UTC, PeterJCLaw commented
I appreciate the desire here, however using the development version of the tools has a number of consequences -- most notably that still-in-development behaviours could end up committed to the inventory repo and thus foisted upon users who may not have (or even be able) to install that version of the tooling.

2023-09-17 19:13 UTC, 8BitJosh approved these changes

2023-09-17 20:02 UTC, RealOrangeOne requested changes
I'm afraid I agree with Peter here. Pinning like this is likely to cause us more headaches in future. Even if what's there now is stable enough for us to use, it might not always be true (although IMO `main` should still be reasonably stable, even if not "production-grade").

I see 3 possible ways forward:

1. Fix `sr.tools` upstream, ship a release, which should then fix CI here (preferred). 
2. Pin to a specific commit. Sure, it's far from ideal, but at least this way we're at a stable-ish version which will more reliably work, even if we do this _whilst_ going with Option 1.
3. Just disable CI. Ignoring CI errors (and communicating that's what people should do) is objectively worse than having no CI.

2023-09-19 19:07 UTC, RealOrangeOne approved these changes
I like this _totally temporary_ solution.

2023-09-19 19:07 UTC, merged